Algoritmo "AlgoritmodeDecisao"
// Disciplina  : Lógica de programação com visualg
// Professor   : Jailson Costa dos Santos
// Descrição   : Exemplo de algoritmo de decisão simples.
// Autor(a)    : Italo Moreno
// Data atual  : 30/03/2026
Var
   // Seção de Declarações das variáveis
   valor1: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Digite um valor: ")
   leia(valor1)
   se valor1 < 10 entao
      escreval("O número digitado é menor que 10!")
   senao


Fimalgoritmo
