Algoritmo "CircunferenciaCirculo"
// Disciplina  : Lógica de programação com visualg
// Professor   : Jailson Costa dos Santos
// Descrição   : Solicita o valor do raio de um circulo e calcula sua circunferência.
// Autor(a)    : Italo Moreno
// Data atual  : 30/03/2026
Var
// Seção de Declarações das variáveis 
   raio: real
   resultado: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite o valor do raio de um círculo: ")
   leia(raio)
   resultado <- 2 * 3.14 * raio
   escreva("O valor da circunferência do circulo é: ",resultado)

Fimalgoritmo