Algoritmo "Soma"
// Disciplina   : [Lógica de Programação com Visualg]
// Professor   : Jailson Costa dos Santos
// Descrição   : Algoritimo solicita dois números inteiros, soma e mostra o resultado
// Autor(a)    : Italo Moreno
// Data atual  : 23/03/2026
Var
// Seção de Declarações das variáveis 
   numero1: inteiro
   numero2: inteiro
   resultado: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva ("Digite o primeiro número inteiro: ")
   Leia (numero1)
   Escreva ("Digite o segundo número inteiro: ")
   Leia (numero2)
   resultado <- numero1 + numero2
   
   Escreva ("A soma dos dois números digitados é: ", resultado)
Fimalgoritmo